"""empty message

Revision ID: 264f3e27f92b
Revises: e256e3ff5ada
Create Date: 2019-05-31 20:28:26.052541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '264f3e27f92b'
down_revision = 'e256e3ff5ada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('violation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_violations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('violation_id', sa.Integer(), nullable=True),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ),
    sa.ForeignKeyConstraint(['violation_id'], ['violation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_violations')
    op.drop_table('violation')
    # ### end Alembic commands ###
