"""empty message

Revision ID: 32e6ce06e5bd
Revises: 836494c4b68f
Create Date: 2019-04-02 20:28:41.086133

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '32e6ce06e5bd'
down_revision = '836494c4b68f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('walker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_pr', sa.Text(), nullable=True),
    sa.Column('address_reg', sa.Text(), nullable=True),
    sa.Column('height', sa.String(length=3), nullable=True),
    sa.Column('weight', sa.String(length=10), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('series', sa.String(length=4), nullable=True),
    sa.Column('number', sa.String(length=6), nullable=True),
    sa.Column('issuedBy', sa.Text(), nullable=True),
    sa.Column('issueDate', sa.DateTime(timezone=4), nullable=True),
    sa.Column('birthDate', sa.DateTime(timezone=4), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('user_walker_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'walker', ['walker_id'], ['id'])
    op.drop_column('user', 'birthDate')
    op.drop_column('user', 'rating')
    op.drop_column('user', 'height')
    op.drop_column('user', 'address_pr')
    op.drop_column('user', 'issueDate')
    op.drop_column('user', 'score')
    op.drop_column('user', 'series')
    op.drop_column('user', 'address_reg')
    op.drop_column('user', 'weight')
    op.drop_column('user', 'number')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'issuedBy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('issuedBy', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('number', sa.VARCHAR(length=6), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('weight', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('address_reg', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('series', sa.VARCHAR(length=4), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('issueDate', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('address_pr', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('height', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('birthDate', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_walker_id_fkey', 'user', 'user', ['walker_id'], ['id'])
    op.drop_table('walker')
    # ### end Alembic commands ###
