"""empty message

Revision ID: 50c722438eea
Revises: 8818b4f70544
Create Date: 2019-04-17 11:22:46.977095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50c722438eea'
down_revision = '8818b4f70544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('avatar_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'file', ['avatar_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'avatar_id')
    op.drop_table('file')
    # ### end Alembic commands ###
