"""empty message

Revision ID: 52ebab265511
Revises: 885a635471fc
Create Date: 2019-04-23 19:52:20.587662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ebab265511'
down_revision = '885a635471fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('archiveDate', sa.DateTime(timezone=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pet', 'archiveDate')
    # ### end Alembic commands ###
