"""empty message

Revision ID: 6011c7ee3f5e
Revises: f3e9a2bdffbd
Create Date: 2019-05-28 12:07:28.767758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6011c7ee3f5e'
down_revision = 'f3e9a2bdffbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('walker', 'gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('walker', sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
