"""request table

Revision ID: 7b4dce664981
Revises: 52ebab265511
Create Date: 2019-05-07 12:29:40.951982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4dce664981'
down_revision = '52ebab265511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('violation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creationDate', sa.DateTime(timezone=4), nullable=True),
    sa.Column('startWalkDate', sa.DateTime(timezone=4), nullable=True),
    sa.Column('timeWalk', sa.Integer(), nullable=True),
    sa.Column('startAuctionDate', sa.DateTime(timezone=4), nullable=True),
    sa.Column('endAuctionDate', sa.DateTime(timezone=4), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('priceN', sa.Integer(), nullable=True),
    sa.Column('priceP', sa.Integer(), nullable=True),
    sa.Column('walker_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('endOwnerDate', sa.DateTime(timezone=4), nullable=True),
    sa.Column('endWalkerDate', sa.DateTime(timezone=4), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.ForeignKeyConstraint(['walker_id'], ['walker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('summa', sa.Integer(), nullable=True),
    sa.Column('creationDate', sa.DateTime(timezone=4), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('walker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ),
    sa.ForeignKeyConstraint(['walker_id'], ['walker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('mark', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('walker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['walker_id'], ['walker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pet_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_violations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('violation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ),
    sa.ForeignKeyConstraint(['violation_id'], ['violation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_violations')
    op.drop_table('pet_requests')
    op.drop_table('review')
    op.drop_table('rate')
    op.drop_table('request')
    op.drop_table('violation')
    op.drop_table('status')
    # ### end Alembic commands ###
