"""walkers  table

Revision ID: 7c3abcda9300
Revises: 4517f6754b8f
Create Date: 2019-04-02 19:37:20.896396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c3abcda9300'
down_revision = '4517f6754b8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address_pr', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('address_reg', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('birthDate', sa.DateTime(timezone=4), nullable=True))
    op.add_column('user', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('height', sa.String(length=3), nullable=True))
    op.add_column('user', sa.Column('id_walker', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('issueDate', sa.DateTime(timezone=4), nullable=True))
    op.add_column('user', sa.Column('issuedBy', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('number', sa.String(length=6), nullable=True))
    op.add_column('user', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('score', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('series', sa.String(length=4), nullable=True))
    op.add_column('user', sa.Column('weight', sa.String(length=10), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['id_walker'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'weight')
    op.drop_column('user', 'series')
    op.drop_column('user', 'score')
    op.drop_column('user', 'rating')
    op.drop_column('user', 'number')
    op.drop_column('user', 'issuedBy')
    op.drop_column('user', 'issueDate')
    op.drop_column('user', 'id_walker')
    op.drop_column('user', 'height')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'birthDate')
    op.drop_column('user', 'address_reg')
    op.drop_column('user', 'address_pr')
    # ### end Alembic commands ###
