"""empty message

Revision ID: 836494c4b68f
Revises: 7c3abcda9300
Create Date: 2019-04-02 20:15:53.667340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836494c4b68f'
down_revision = '7c3abcda9300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('walker_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_id_walker_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'user', ['walker_id'], ['id'])
    op.drop_column('user', 'id_walker')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id_walker', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_id_walker_fkey', 'user', 'user', ['id_walker'], ['id'])
    op.drop_column('user', 'walker_id')
    # ### end Alembic commands ###
