"""empty message

Revision ID: 885a635471fc
Revises: 50c722438eea
Create Date: 2019-04-17 12:47:55.042105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885a635471fc'
down_revision = '50c722438eea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('avatar_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pet', 'file', ['avatar_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pet', type_='foreignkey')
    op.drop_column('pet', 'avatar_id')
    # ### end Alembic commands ###
