"""empty message

Revision ID: 911d5835d987
Revises: e3615a83ea32
Create Date: 2019-05-09 16:05:07.353730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '911d5835d987'
down_revision = 'e3615a83ea32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status', sa.Column('key', sa.String(length=50), nullable=True))
    op.drop_column('status', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('status', 'key')
    # ### end Alembic commands ###
