"""users table

Revision ID: bbdbfb891ef7
Revises: 
Create Date: 2019-03-24 21:51:27.682780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbdbfb891ef7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=25), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=100), nullable=True),
    sa.Column('surname', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('middlename', sa.String(length=50), nullable=True),
    sa.Column('vkid', sa.Integer(), nullable=True),
    sa.Column('addres', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.Column('creationDate', sa.DateTime(timezone=4), nullable=True),
    sa.Column('deletionDate', sa.DateTime(timezone=4), nullable=True),
    sa.Column('lastLoginDate', sa.DateTime(timezone=4), nullable=True),
    sa.Column('isConfirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('roles_fk', sa.Integer(), nullable=True),
    sa.Column('users_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['roles_fk'], ['role.id'], ),
    sa.ForeignKeyConstraint(['users_fk'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
